weights: .\runs\train\exp1\weights\last.pt
cfg: ''
data: data/coco128.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 1120
batch_size: 4
img_size:
- 640
- 640
resume: true
nosave: false
notest: false
workers: 0
device: '0'
single_cls: false
rect: false
noautoanchor: false
evolve: false
multi_scale: true
label_smoothing: 0.0
adam: false
sync_bn: false
linear_lr: false
cache_images: false
image_weights: true
bucket: ''
project: runs/train
name: exp
exist_ok: false
quad: false
save_period: 1
artifact_alias: latest
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
save_dir: runs\train\exp1
